### PR TITLE
Update dependencies and fix clip issue

### LINKED ISSUE #10: Dragging not possible anymore on non-touch devices
Dragging of split slider is not possible (anymore) due to an incorrect assumption of the L.Browser module.

```
on(range, L.Browser.touch ? 'touchstart' : 'mousedown', cancelMapDrag, this)

on(range, L.Browser.touch ? 'touchend' : 'mouseup', uncancelMapDrag, this)
```

Tested with Google Chrome 105.0.5195.102 and version earlier.
Android/iOS is still working, only desktop browsers are affected.

Background;:

L.Browser.touch stays true even if you are using a non-touch device. It would be better to rely on global window variable like other leaflet plugins.

### PR DESCRIPTION
**Pull request by oxidase**
The PR updates dependencies, fixes #10 and changes version to v1.0.3

Duplicates: #11

### CODE REVIEW

**Comment by gmaclennan** [comment]
I'm not a maintainer here. I think this is a fork from a module I wrote a while ago and the package.json has not been updated.

**Comment by oxidase** [comment]
sorry for noice!
 
@SylvainCorlay @martinRenou pls, could you check and publish?

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
I just published the release! Thanks a lot for doing this

**Pull request merged**
